// src/components/RoadmapDisplay.jsx

import React from 'react';
import ReactFlow, { Background, Controls, MiniMap } from 'reactflow';
import 'reactflow/dist/style.css';
import './RoadmapDisplay.css'; 

const RoadmapDisplay = ({ data }) => {
  if (!data || !data.nodes || data.nodes.length === 0) {
    return (
      <div className="roadmap-container">
        <div className="roadmap-header">
          <h2>Generating Roadmap...</h2>
          <p>Please wait while the AI crafts your personalized plan.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="roadmap-container">
      <div className="roadmap-header">
        <h2>Your Personalized Roadmap</h2>
        <p>Here is the strategic plan generated by the AI based on your answers.</p>
      </div>
      <div className="roadmap-viewport">
        <ReactFlow
          nodes={data.nodes}
          edges={data.edges}
          fitView
          nodesDraggable={true} // Allow users to move nodes
          nodesConnectable={false}
          proOptions={{ hideAttribution: true }} // Hides the "React Flow" attribution
        >
          <Background variant="dots" gap={12} size={1} />
          <Controls />
          <MiniMap nodeColor="#007bff" nodeStrokeWidth={3} zoomable pannable />
        </ReactFlow>
      </div>
    </div>
  );
};

export default RoadmapDisplay;